near/near-lake-framework-rs

- Cargo.toml
- src/lib.rs
- src/s3_fetchers.rs
- src/types.rs
* `start_block_height` is required on the NEAR Lake Framework side, according to the decision made in #3 
* Increase the number of keys retrieved from S3 to 1000
* Improve performance around awaiting by introducing `FuturesOrdered`
Also, I've added error logs instead of some `.unwrap()`s but I haven't come up with the answer to what do we want to do in case of that errors.
> refactor: Make `start_block_height` required. Add error logs instead of `.unwrap()`

- Cargo.toml
- src/lib.rs
- src/s3_fetchers.rs
* We had a bug that will return the last available block over and over again until the new one appears on S3 - fixed
* On NEAR Lake we have changed the naming convention to handle string sorting properly https://github.com/near/near-lake/pull/24. Addressed this on the framework side as well
> refactor: Add leading zeros. Avoid returning the same block over and over again

- src/s3_fetchers.rs
In order to research and resolve the issue https://github.com/near/near-lake/issues/22 we need to configure buckets' policies and include `request_payer` to the S3 calls. 
This PR enables the `request_payer`
> refactor: Add RequestPayer to S3 calls to enable the access to anyone who is ready to pay

- src/lib.rs
In order to ensure we process data from S3 consistently and don't allow any possible "gaps" (e.g. having a few NEAR Lake nodes where one is storing fresher block while another still saving one of the previous), we compare the last processed block hash with `prev_hash` from the current block
> feat: Ensure prev_hash matches the previously processed block for data consistency

- Cargo.toml
- README.md
- src/lib.rs
- src/types.rs
Additionally for custom S3 endpoint into Near Lake Indexer https://github.com/near/near-lake/pull/29
It world be great to have the same feature for near-lake-framefork. That allow users to setup fully cloud agnostic environment through Localstack or Minio S3 compatible server.
> Add option for custom s3 endpoint

- src/s3_fetchers.rs
This resolves #18 
A little bit of a context:
On the NEAR Lake side, we're storing the `shard_N.json` file even if the Block misses a Chunk. But we had an issue where `StateChanges` were a part of a Block not a Chunk in the early blocks. Now, this issue is fixed, and no **new** `StateChanges` appear in a Block itself. 
We decided that it's better to receive an empty `IndexerShard` in the stream than miss `StateChanges`.
> refactor: Fetch shard_N.json based on block.chunks.len

- src/lib.rs
If there are any S3 errors, such as invalid credentials, the framework currently results in a tight loop printing error messages that do not provide the actual error. This pull request adds the underlying S3 error to the output, and adds a 1s sleep to prevent a tight loop in this scenario.
Before:
```
May 10 16:13:16.754 DEBUG near_lake_framework: Fetching blocks from S3, after 87868917...
May 10 16:13:16.754 ERROR near_lake_framework: Failed to list objects from bucket near-lake-data-testnet. Retrying...
May 10 16:13:16.754 DEBUG near_lake_framework: Fetching blocks from S3, after 87868917...
May 10 16:13:16.754 ERROR near_lake_framework: Failed to list objects from bucket near-lake-data-testnet. Retrying...
May 10 16:13:16.754 DEBUG near_lake_framework: Fetching blocks from S3, after …
```
> An improvement to S3 error handling

- CHANGELOG.md
- README.md
- src/lib.rs
This changes the error handling in the streamer to expose a way to handle errors that occur on the sender, instead of using `panic()`.
**Note: this is a breaking change to `streamer()`, to now return a tuple instead of a single value.**
Example of cleanly terminating the stream after reaching some maximum block height:
```rust
// instantiate the NEAR Lake Framework Stream
let (sender, stream) = near_lake_framework::streamer(config);
// We will stop streaming after this block height
let max_height = 1234567;
// read the stream events and pass them to a handler function with
// concurrency 1
let mut handlers = tokio_stream::wrappers::ReceiverStream::new(stream)
.take_while(|streamer_message| {
let in_range = streamer_message.block.header.height <= max_height;
async move { in_range }
}) …
```
> Remove panics in streamer, allow stream to be stopped gracefully

- Cargo.toml
Addresses #34 by requiring higher minimum version of `serde_json`
> fix: Bump version for `serde_json`

- src/lib.rs
As I've been running an indexer using this framework, on occasion I've seen these errors in the logs. As far as I can tell, the framework recovers automatically after retrying (sometimes after _several_ retries in a row). Since it _does_ recover automatically, I propose changing these logs to `warn` instead of `error` ... reserving `error` only for situations that require  manual intervention; i.e. where data loss has occurred (if the framework detects a missing block, stops streaming altogether, etc.)
> Change to tracing::warn instead of tracing::error for retryable errors

- CHANGELOG.md
- Cargo.toml
This will help the downstream projects avoid duplicate versions of near-primitives and their dependencies.
> chore: Extended the list of supported near-primitives versions from 0.12.0 to >=0.12.0,<0.15.0

- CHANGELOG.md
- src/lib.rs
- src/s3_fetchers.rs
- src/types.rs
This was inspired by https://github.com/near/near-lake-framework-js/pull/4, but so far in my testing I actually hit the network limit sooner than this streaming limitation when I am testing it on the server (it can reach 1000 bps but then stuck for 5-10 seconds waiting for some delayed response). This approach is still more tolerant to sudden delays and it appears to be working better for the account activity indexer (where there is some actual block processing happening). Ultimately, I saw 150-450 bps on the current master branch and 150-600 bps on this PR branch when the block processing is actually just a print statement.
This also should cut the AWS costs on re-indexing since we do fewer ListObjectV2 calls (previously we called it with the limit of 100 keys, which is only 20 blocks …
> feat: improved streaming

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
It is extremely hard to make benchmarks over S3. My results were quite unstable throughout the day (I used two servers: one in the US and another in Europe), and at some point, these changes showed significantly worse results, but now they show superior and stable results beating the best results I saw today.
The results from the US server seemed to be completely useless from the benchmark point of view, but then it seems the variance is quite high even when using a server in Europe (I run all the tests for 1-2 minutes several times in a row):
* 0.5.0 version was reaching 150-200 bps in the morning and now
* this PR hit the limit of 90-100 bps in the morning, but now it reaches 210-220 bps
* near-lake-framework-js reaches 34-42 bps
* near-lake-framework-py reaches 6-14 bps
Given that our …
> feat: Avoid spiky latency with streaming block heights preload

- CHANGELOG.md
- src/lib.rs
I have tested it on the same benchmark as #44, and the results are quite unstable, but overall it is quite fast anyway and I don't see spikes, which is good.
I believe we should release a new patch release as soon as this PR lands.
> fix: Fixed the issue of messages being constantly delayed by 100 blocks

- CHANGELOG.md
- Cargo.toml
This PR upgrades NEAR Lake Framework to 0.6.0 version.
This upgrade introduces a breaking change since this version underlying `near-indexer-primitives` of versions between 0.15 and 0.16 is allowed.
`near-indexer-primitives` reflects some breaking changes in the data types. Some of the fields that were previously
a base64-encoded String that now became raw `Vec<u8>`:
- `views::ActionView::FunctionCall.args`
- `views::QueryResponseKind::ViewState`
- `views::ExecutionStatusView::SuccessValue`
**Refer to this [`nearcore` commit](https://github.com/near/nearcore/commit/8e9be9fff4d520993c81b0e3738c0f223a9538c0) to find all the changes of this kind.**
Resolves #48
> chore: Release 0.6.0, upgrade near-indexer-primitives dependency

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
- src/s3_fetchers.rs
- src/types.rs
In this PR I am doing a few tweaks here and there:
- ~~Dropped a redundant loop that was left after the Block Heights "buffer" feature introduction~~ (that loop appears to be needed)
- Renamed a few internal methods to reflect what they do
- Added debug and error logs in a few places
- Introduced a `LakeError` enum using `thiserror` (#42), but not exposing it yet to avoid breaking changes to the framework (for now, will be added to [0.7.0](https://github.com/near/near-lake-framework-rs/milestone/3))
- Added proper error handling in a few places
- Updated the dependencies version of AWS crates
I am aiming for these changes to be released soon in the `0.6.1` version
> refactor: Internal renaming, more logs, proper error handling

- CHANGELOG.md
- Cargo.toml
- Fix of possible silent stops of the streamer (firing logs and returning errors where necessary)
- Fix the issue the streamer was always 1 block behind
- Renamed a few internal methods to reflect what they do
- Added debug and error logs in a few places
- Introduced a `LakeError` enum using `thiserror` (#42), but not exposing it yet to avoid breaking changes to the framework (for now, it will be done in `0.7.0`)
- Added proper error handling in a few places
- Updated the dependencies version of AWS crates
> chore: Update NEAR Lake Framework to 0.6.1

- CHANGELOG.md
- Cargo.toml
- src/types.rs
This PR adds support for the new meta transactions/delegate actions by upgrading `near-indexer-primitives`. This is a breaking change as the `ActionView` `enum` now has the new `Delegate` variant which must be handled.
I've also added a helper method to connecting to `betanet` Lake, similar to what we have for `mainnet`/`testnet`. This will help with testing meta transactions.
> feat: Support Meta transactions

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- blocks/000000879765/block.json
- blocks/000000879765/shard_0.json
- src/lib.rs
- src/s3_fetchers.rs
This PR introduces tests for `s3_fetchers`, with the goal of testing the deserialization of meta transactions. It does this by creating a new `trait` to abstract away `aws_sdk_s3::Client` providing the ability to inject fake implementations which have mock S3 responses.
I've also added another step to the existing github action which will run the tests.
> test: Meta transaction deserialization

- CHANGELOG.md
- src/types.rs
The PR https://github.com/near/near-lake-framework-rs/pull/57 enabling a new shortcut for `betanet` assumed the corresponding S3 bucket will be created in the same region as the other buckets. 
Surprisingly, the `near-lake-data-betanet` was created in a different region and the shortcut became broken.
This PR fixes it and adds a corresponding changelog record so we can create and publish a minor release (0.7.1)
> fix: Betanet shortcut default region fixed

- CHANGELOG.md
- Cargo.toml
This is a minor release that basically allows you to run an indexer against `betanet` (if you need, of course, we need it)
> chore: Release 0.7.1

- README.md
- src/lib.rs
I've invested some time into more precise price calculations. 
Recently I've started to receive some complains that it is too expensive to indexer the entire `mainnet` history and figures I've got from people were $3k-4k to index the history.
I am adding the tables and explanations with an updated more accurate cost estimation to the README.
Spoiler: Today indexing the entire `mainnet` history would cost around $170 (let's say $200 assuming some requests to S3 might fail and be retried)
> chore: README update with more precise calculations

- README.md
- src/lib.rs
- Fixed a year (2022 -> 2023, I seem to be living in the past)
- Added notes explaining the magic numbers (number of blocks per day, per month)
> chore: README cost estimates. Fix year, explain magic numbers a bit

- lake-framework/README.md
- lake-framework/src/lib.rs
- lake-framework/src/types.rs
This PR is aiming at the `dev-0.8.8` branch and updates the READMEs, fixes code examples to pass doc tests.
BTW partially resolving #52 (Lake Framework documentation update, though might be changed closer to the release)
The output looks perfect :)
```
Running unittests src/lib.rs (target/debug/deps/near_lake_framework-32dcaeaff76ac223)
running 1 test
test s3_fetchers::test::deserializes_meta_transactions ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running unittests src/lib.rs (target/debug/deps/near_lake_primitives-2c87358ec0ad3e20)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Doc-tests near-lake-framework
running 11 tests
test src/lib.rs - types::Lake (line 19) - …
```
> fix(tests): Resolved #60: Fix failing doc tests

- lake-framework/Cargo.toml
- lake-framework/README.md
- lake-framework/examples/actions.rs
- lake-framework/examples/nft_indexer.rs
- lake-framework/examples/simple.rs
- lake-framework/examples/with_context.rs
- lake-framework/src/lib.rs
- lake-framework/src/s3_fetchers.rs
- lake-framework/src/streamer.rs
- lake-framework/src/types.rs
This PR finishes the work regarding #42 for 0.8.8 (https://github.com/near/near-lake-framework-rs/milestone/3)
- A little bit refactored `LakeError` that includes all possible errors from the library
- Replace all `anyhow` usage with `LakeError`
- Update the README and code snippets, since the API is changed a little bit (no big deal since this release is going to introduce a huge breaking change anyway)
**Attention!** This PR's base branch is set to this PR #68 so it's better to merge this one before that.
> refactor: Resolves #42 replace anyhow with LakeError enum (thiserror)

- lake-framework/src/lib.rs
- lake-framework/src/types.rs
We used to have a hardcoded value for the block-processing concurrency. It was 1 by default since it is the most convenient for most indexers since most block-processing logic depends on the previous blocks.
Today, we expose a configuration parameter for the `concurrency` (default is still `1`).
```rust
LakeBuild::default()
.mainnet()
.start_block_height(0)
.concurrency(1_000)
.build()
.unwrap()
.run(handle_block)
```
Please be aware that the concurrency should be increased only if your block-processing logic is independent of the previously processed blocks. Otherwise, your indexer will be stuck.
> feat: Expose concurrency parameter to the Lake structure (and builder)

- CHANGELOG.md
- Cargo.toml
- Update near primitives crates to version `0.17.0`
- Update `tokio` version to the latest (`1.28.2`)
- Bump version of the Lake Framework to `0.7.2`
> chore: 0.7.2 release

- Cargo.toml
- lake-context-derive/Cargo.toml
- lake-context-derive/README.md
- lake-context-derive/src/lib.rs
- lake-framework/Cargo.toml
- lake-framework/README.md
- lake-framework/examples/with_context.rs
- lake-framework/examples/with_context_parent_tx_cache.rs
- lake-framework/output.txt
- lake-framework/src/lib.rs
- lake-framework/src/types.rs
- lake-parent-transaction-cache/Cargo.toml
- lake-parent-transaction-cache/README.md
- lake-parent-transaction-cache/src/lib.rs
- lake-primitives/README.md
- lake-primitives/src/lib.rs
During the implementation of the #71 proposal I've realized that while it is still possible to proceed with the middleware concept, in the end, we will have pretty complex middleware for developers to write.
Thus, I've decided to give up on middlewares in favor of Contexts. In this PR I'm introducing the first-ever shareable context written for the Lake Framework RS
```rust
fn main () {
let parent_transaction_cache_ctx = ParentTransactionCacheBuilder::default()
.build()
.expect("Failed to build the ParentTransactionCache context");
LakeBuilder::default()
.mainnet()
.start_block_height(80504433)
.build()
.expect("Failed to build the Lake Framework")
.run_with_context(handle_block, &parent_transaction_cache_ctx)
.expect("Failed to run the Lake Framework");
}
async fn handle_block(
mut …
```
> feat: ParentTransactionCache context and example

- Cargo.toml
- lake-primitives/Cargo.toml
- lake-primitives/src/types/delegate_actions.rs
- lake-primitives/src/types/impl_actions.rs
Update the near primitives' crates to the 0.17.0 version (latest `nearcore` release `1.34.0`)
Note, the 0.17.0 version of the primitives introduced a wrapper(s) around some `Vec<u8>` for readability. However, I don't have an opinion on whether we should follow that in our simplified structures, thus I convert them into `Vec<u8>`. This might change on the release.
> chore: Upgrade near primitives to 0.17.0 version

- .github/workflows/ci.yml
- lake-context-derive/Cargo.toml
- lake-context-derive/README.md
- lake-framework/Cargo.toml
- lake-framework/README.md
- lake-framework/examples/with_context_parent_tx_cache.rs
- lake-framework/src/lib.rs
- lake-framework/src/types.rs
- lake-parent-transaction-cache/Cargo.toml
- lake-parent-transaction-cache/README.md
In this PR I am fixing the naming of the crates by adding the missing `near-` prefix to follow the "naming convention" we have.
Along with fixing the doc-strings and examples by updating imports, I've caught a few bugs here and there and fixed them.
Since we have a test or a few and all the docs are expected to pass the tests I've added back the `test` action to the CI.
> chore: Rename crates adding `near-` prefix to follow the naming. Fix doc-tests

- Cargo.toml
* `near-lake-framework`: 0.8.0-beta.1 -> 0.8.0-beta.2 (✓ API compatible changes)
* `near-lake-context-derive`: 0.8.0-beta.1 -> 0.8.0-beta.2
* `near-lake-parent-transaction-cache`: 0.8.0-beta.1 -> 0.8.0-beta.2
<details><summary><i><b>Changelog</b></i></summary><p>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
> chore: release

- README.md
I guess it's time to replace the link to the original announcement of the NEAR Lake Framework release with the up-to-date release of a new version (0.8.0 high-level update)
> chore(readme): Update the announcement link mentioned in the README

- CHANGELOG.md
- Cargo.toml
- lake-framework/Cargo.toml
- lake-framework/README.md
- lake-framework/src/s3_fetchers.rs
- lake-framework/src/types.rs
This PR introduced **beta.3** for 0.8.0 version
> chore: Upgrade AWS SDK dependencies

- CHANGELOG.md
- Cargo.toml
- src/s3_fetchers.rs
- src/types.rs
We're still on `0.7.x` and not quite ready to upgrade to `0.8.x`. This PR upgrades the `aws-*` crates on the `0.7.x` branch to the latest version, as there is some newer functionality that we require.
> chore: Upgrade `aws` crates to latest version

- CHANGELOG.md
- Cargo.toml
- src/s3_fetchers.rs
- src/types.rs
This PR should address #97 and bump the version of the crate to 0.7.5
I had to extract the code from the infinity loops of `fetch_block_or_retry` and a similar function for the shards.
I made two new functions: `fetch_block` and `fetch_shard`, and made them public.
> refactor(0.7.x): 0.7.5 with exposed non-retryable s3_fetchers

- Cargo.toml
In this PR: 
1. Upgraded dependencies versions
2. Upgraded NEAR crates to 0.20.0 release
> chore: Upgraded dependencies

- CHANGELOG.md
- Cargo.toml
near-lake-framework 0.7.5 -> 0.7.6
1. Bump version
2. Update CHANGELOG
> chore: release v0.7.6

- CHANGELOG.md
- Cargo.toml
- src/s3_fetchers.rs
near-lake-framework 0.7.6 -> 0.7.7
Make `list_block_heights` public
Bump version
Update CHANGELOG
> chore: release v0.7.7

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/s3_client.rs
- src/s3_fetchers.rs
- src/types.rs
Previously, the `S3Client` trait is used to mock requests made to S3 so that we can unit test our S3 related logic. This PR allows custom implementations of this trait to be configured and used within Lake Framework. This grants users greater control over the S3 requests made, which would otherwise not be possible via configuration of `s3_config` alone. The main motive for this change is to add caching of requests, but the solution is generic enough that it could be extended to many different use cases.
`S3Client` has been updated to make it easier to work with from external crates. Previously, it was a thin wrapper over `GetObject` and `ListObjects`, but it has been abstracted further so the user does not have to deal with the complex return types of these operations.
On success, the …
> feat: Allow custom configuration of `S3Client`

- CHANGELOG.md
- Cargo.toml
* Upgrade `near-indexer-primitives` to `0.23.0` (nearcore-1.40.0)
* Expose `s3_client::S3Client` trait so that custom S3 client implementations can be configured via `LakeConfigBuilder::s3_client`
* Errors returned from public `s3_fetcher` methods have changed slightly to support the newly exposed `S3Client`. As these methods serve a rare use-case this is only a minor bump.
> chore: Release 0.7.9 with support of nearcore 1.40.0

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/providers/fastnear/client.rs
- src/providers/fastnear/types.rs
- src/providers/mod.rs
* Upgrade `near-indexer-primitives` to `0.28.0` (nearcore-2.4.0)
* Updated `FastNearClient` to include `authorization_token` in the headers
> add fastnear authorization_token supports

- lake-framework/src/lib.rs
Adds in this additional function `run_with_context_async` such that users can run lake indexer framework on top of their own runtime, managing the underlying task themselves, such as being able to abort the task and cancel it.
> feat: add async run_with_context
